eye_catch_types:
  - name: "none"
    human_name: "なし"
  - name: "header_area"
    human_name: "ヘッダー領域"
    location: "header"
  - name: "header_area_banner"
    human_name: "ヘッダー領域（バナータイプ）"
    location: "header"
  - name: "content_area"
    human_name: "コンテンツ領域"
    location: "container"
#  - name: "main_area"
#    human_name: "メイン領域"
#    location: "contents"
